#!/bin/sh

# First, determine where we are
if test -f $0; then
  ops_bindir=`dirname $0`
  ops_bindir=`cd $ops_bindir; pwd`
  export OPS_HOME=`dirname $ops_bindir`
else
  ops=`which ops`
  if "x$ops" = "x"; then
    echo "Error: ops is not in the path"
    exit 1;
  fi

  ops_bindir=`dirname $ops`
  export OPS_HOME=`dirname $ops_bindir`  
fi

uname_o=`uname -o`
uname_m=`uname -m`
if test $uname_o = "Msys" || test $uname_o = "Cygwin"; then
  if test $uname_m = "x86_64"; then
    OPS_PLATFORM=win64
  else
    OPS_PLATFORM=win32
  fi
else
OPS_PLATFORM=linux_x86_64
fi

export LD_LIBRARY_PATH=${OPS_HOME}/${OPS_PLATFORM}/lib:${LD_LIBRARY_PATH}

exec ${OPS_HOME}/${OPS_PLATFORM}/bin/ops "$@"
